### ISSUE TITLE
SVG not inlined in production build

### ISSUE THREAD

**Issue by richardtallent** [visualfanatic/vite-plugin-svg#12]
Using vite v1.0.0-rc.9

I'm trying to build my entire web application in a single file (it's a strange approach, but this is for an offline file-based web app, not served from a web server). My vite.config.js file includes:

```
const svgPlugin = require("vite-plugin-svg")
module.exports = {
	assetsInlineLimit: 100000000,
	cssCodeSplit: false,
	outputOptions: { inlineDynamicImports: true, },
	plugins: [svgPlugin()],
}
```

I'm then using the plugin like this:

```
<template>... <MySvgFile/>...</template>
<script>
import { VueComponent as MySvgFile } from "../svg/my-svg-file.svg"
export default {
	components: { MySvgFile },
}
</script>
```

This is working, but when I run `npm run build`, the SVG file is emitted to the `dist/_assets` folder (with a hashed filename) rather than being inlined into the component and included as part of the built index.js file.

Is there an option I'm missing to enable this behavior?

**Comment by visualfanatic** [comment]
@richardtallent the svg file will be emitted, because of the Vite's way of handling images, but it will not be used.

**Comment by richardtallent** [comment]
I finally got a chance to work on this again, and I can confirm the SVG is embedded in the bundled JavaScript, which is perfect for my use case. Thanks!
