### ISSUE TITLE
Support vite 1.0.0-beta

### ISSUE THREAD

**Issue by mesqueeb** [visualfanatic/vite-plugin-svg#4]
the latest Vite version is `1.0.0-beta.4`, I'd love support for the beta, as I think that the beta will be closer to the final proposed Vite syntax than `0.20.8`.

Great plugin!!

**Comment by visualfanatic** [comment]
Hey @mesqueeb, I just released `vite-plugin-svg@0.5.0`, it supports Vite `1.0.0-beta.4` and fixes #3!
